/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package esquemas;

/**
 *
 * @author Usuario
 */
public class EsquemasCombinados extends javax.swing.JFrame {

    /**
     * Creates new form EsquemasCombinados
     */
    public EsquemasCombinados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        scrTexto = new javax.swing.JScrollPane();
        TxtADatos = new javax.swing.JTextArea();
        pnlSur = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        pnlOeste = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Boton 1");
        pnlNorte.add(jButton1);

        jButton2.setText("Boton 2");
        pnlNorte.add(jButton2);

        jButton3.setText("Boton 3");
        pnlNorte.add(jButton3);

        jButton4.setText("Boton 4");
        pnlNorte.add(jButton4);

        getContentPane().add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        TxtADatos.setColumns(20);
        TxtADatos.setRows(5);
        scrTexto.setViewportView(TxtADatos);

        getContentPane().add(scrTexto, java.awt.BorderLayout.CENTER);

        jButton6.setText("Boton5");
        pnlSur.add(jButton6);

        jTextField1.setColumns(10);
        pnlSur.add(jTextField1);

        getContentPane().add(pnlSur, java.awt.BorderLayout.PAGE_END);

        pnlOeste.setLayout(new java.awt.GridLayout(4, 2));

        jButton5.setText("jButton5");
        pnlOeste.add(jButton5);

        jLabel2.setText("jLabel2");
        pnlOeste.add(jLabel2);

        jCheckBox1.setText("jCheckBox1");
        pnlOeste.add(jCheckBox1);

        jRadioButton1.setText("jRadioButton1");
        pnlOeste.add(jRadioButton1);

        getContentPane().add(pnlOeste, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EsquemasCombinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EsquemasCombinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EsquemasCombinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EsquemasCombinados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EsquemasCombinados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtADatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlOeste;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JScrollPane scrTexto;
    // End of variables declaration//GEN-END:variables
}
